-- Schema for non-domestic EPC certificates
-- Column order matches CSV header from bulk download files
CREATE TABLE IF NOT EXISTS non_domestic_certificates (
    certificate_number VARCHAR,
    address1 VARCHAR,
    address2 VARCHAR,
    address3 VARCHAR,
    postcode VARCHAR,
    uprn VARCHAR,
    asset_rating INTEGER,
    asset_rating_band VARCHAR,
    property_type VARCHAR,
    inspection_date DATE,
    local_authority VARCHAR,
    constituency VARCHAR,
    transaction_type VARCHAR,
    lodgement_date DATE,
    new_build_benchmark DOUBLE,
    existing_stock_benchmark DOUBLE,
    building_level VARCHAR,
    main_heating_fuel VARCHAR,
    other_fuel_desc VARCHAR,
    special_energy_uses VARCHAR,
    renewable_sources VARCHAR,
    floor_area DOUBLE,
    standard_emissions DOUBLE,
    target_emissions DOUBLE,
    typical_emissions DOUBLE,
    building_emissions DOUBLE,
    aircon_present VARCHAR,
    aircon_kw_rating DOUBLE,
    estimated_aircon_kw_rating DOUBLE,
    ac_inspection_commissioned VARCHAR,
    building_environment VARCHAR,
    address VARCHAR,
    local_authority_label VARCHAR,
    constituency_label VARCHAR,
    posttown VARCHAR,
    lodgement_datetime TIMESTAMP,
    primary_energy_value DOUBLE,
    report_type VARCHAR,
    uprn_source VARCHAR
);
