-- Incremental certificate updates.
-- Invoked by scripts/run_updates.py — do not run directly unless BOTH
-- data/updates/domestic/*.csv AND data/updates/non-domestic/*.csv exist
-- (read_csv errors on an empty glob).
--
-- Strategy: ANTI JOIN insert against certificate_number — equivalent to
-- ON CONFLICT DO NOTHING but works without a PRIMARY KEY on the target.
-- The wrapper extracts each statement by its `-- @<key>` marker and runs
-- it independently, so directories with no files are skipped.

-- @domestic
INSERT INTO domestic_certificates
SELECT s.*
FROM read_csv('data/updates/domestic/*.csv', header=true, escape='\', strict_mode=false, parallel=false, columns={
    'certificate_number': 'VARCHAR',
    'address1': 'VARCHAR',
    'address2': 'VARCHAR',
    'address3': 'VARCHAR',
    'address': 'VARCHAR',
    'postcode': 'VARCHAR',
    'inspection_date': 'DATE',
    'uprn': 'VARCHAR',
    'environment_impact_potential': 'INTEGER',
    'energy_consumption_current': 'DOUBLE',
    'energy_consumption_potential': 'DOUBLE',
    'environment_impact_current': 'INTEGER',
    'co2_emissions_current': 'DOUBLE',
    'co2_emiss_curr_per_floor_area': 'DOUBLE',
    'co2_emissions_potential': 'DOUBLE',
    'total_floor_area': 'DOUBLE',
    'lodgement_date': 'VARCHAR',
    'report_type': 'VARCHAR',
    'posttown': 'VARCHAR',
    'lodgement_datetime': 'TIMESTAMP',
    'current_energy_efficiency': 'INTEGER',
    'current_energy_rating': 'VARCHAR',
    'potential_energy_efficiency': 'INTEGER',
    'potential_energy_rating': 'VARCHAR',
    'extension_count': 'INTEGER',
    'number_open_fireplaces': 'INTEGER',
    'number_heated_rooms': 'INTEGER',
    'number_habitable_rooms': 'INTEGER',
    'low_energy_lighting': 'INTEGER',
    'low_energy_fixed_lighting_outlets_count': 'INTEGER',
    'solar_water_heating_flag': 'VARCHAR',
    'mechanical_ventilation': 'VARCHAR',
    'tenure': 'VARCHAR',
    'property_type': 'VARCHAR',
    'transaction_type': 'VARCHAR',
    'construction_age_band': 'VARCHAR',
    'built_form': 'VARCHAR',
    'energy_tariff': 'VARCHAR',
    'glazed_type': 'VARCHAR',
    'glazed_area': 'VARCHAR',
    'heat_loss_corridor': 'VARCHAR',
    'main_fuel': 'VARCHAR',
    'unheated_corridor_length': 'VARCHAR',
    'floor_level': 'VARCHAR',
    'flat_top_storey': 'VARCHAR',
    'flat_storey_count': 'INTEGER',
    'mains_gas_flag': 'VARCHAR',
    'photo_supply': 'DOUBLE',
    'wind_turbine_count': 'INTEGER',
    'lighting_cost_current': 'INTEGER',
    'lighting_cost_potential': 'INTEGER',
    'heating_cost_current': 'INTEGER',
    'heating_cost_potential': 'INTEGER',
    'hot_water_cost_current': 'INTEGER',
    'hot_water_cost_potential': 'INTEGER',
    'multi_glaze_proportion': 'INTEGER',
    'hotwater_description': 'VARCHAR',
    'hot_water_energy_eff': 'VARCHAR',
    'hot_water_env_eff': 'VARCHAR',
    'floor_description': 'VARCHAR',
    'floor_energy_eff': 'VARCHAR',
    'floor_env_eff': 'VARCHAR',
    'roof_description': 'VARCHAR',
    'roof_energy_eff': 'VARCHAR',
    'roof_env_eff': 'VARCHAR',
    'walls_description': 'VARCHAR',
    'walls_energy_eff': 'VARCHAR',
    'walls_env_eff': 'VARCHAR',
    'windows_description': 'VARCHAR',
    'windows_energy_eff': 'VARCHAR',
    'windows_env_eff': 'VARCHAR',
    'secondheat_description': 'VARCHAR',
    'sheating_energy_eff': 'VARCHAR',
    'sheating_env_eff': 'VARCHAR',
    'mainheat_description': 'VARCHAR',
    'mainheat_energy_eff': 'VARCHAR',
    'mainheat_env_eff': 'VARCHAR',
    'mainheatcont_description': 'VARCHAR',
    'mainheatc_energy_eff': 'VARCHAR',
    'mainheatc_env_eff': 'VARCHAR',
    'lighting_description': 'VARCHAR',
    'lighting_energy_eff': 'VARCHAR',
    'lighting_env_eff': 'VARCHAR',
    'fixed_lighting_outlets_count': 'INTEGER',
    'floor_height': 'DOUBLE',
    'main_heating_controls': 'VARCHAR',
    'local_authority': 'VARCHAR',
    'local_authority_label': 'VARCHAR',
    'constituency_label': 'VARCHAR',
    'constituency': 'VARCHAR',
    'country': 'VARCHAR',
    'region': 'VARCHAR',
    'uprn_source': 'VARCHAR'
}) s
ANTI JOIN domestic_certificates t USING (certificate_number);

-- @non-domestic
INSERT INTO non_domestic_certificates
SELECT s.*
FROM read_csv('data/updates/non-domestic/*.csv', header=true, escape='\', strict_mode=false, parallel=false, columns={
    'certificate_number': 'VARCHAR',
    'address1': 'VARCHAR',
    'address2': 'VARCHAR',
    'address3': 'VARCHAR',
    'postcode': 'VARCHAR',
    'uprn': 'VARCHAR',
    'asset_rating': 'INTEGER',
    'asset_rating_band': 'VARCHAR',
    'property_type': 'VARCHAR',
    'inspection_date': 'DATE',
    'local_authority': 'VARCHAR',
    'constituency': 'VARCHAR',
    'transaction_type': 'VARCHAR',
    'lodgement_date': 'DATE',
    'new_build_benchmark': 'DOUBLE',
    'existing_stock_benchmark': 'DOUBLE',
    'building_level': 'VARCHAR',
    'main_heating_fuel': 'VARCHAR',
    'other_fuel_desc': 'VARCHAR',
    'special_energy_uses': 'VARCHAR',
    'renewable_sources': 'VARCHAR',
    'floor_area': 'DOUBLE',
    'standard_emissions': 'DOUBLE',
    'target_emissions': 'DOUBLE',
    'typical_emissions': 'DOUBLE',
    'building_emissions': 'DOUBLE',
    'aircon_present': 'VARCHAR',
    'aircon_kw_rating': 'DOUBLE',
    'estimated_aircon_kw_rating': 'DOUBLE',
    'ac_inspection_commissioned': 'VARCHAR',
    'building_environment': 'VARCHAR',
    'address': 'VARCHAR',
    'local_authority_label': 'VARCHAR',
    'constituency_label': 'VARCHAR',
    'posttown': 'VARCHAR',
    'lodgement_datetime': 'TIMESTAMP',
    'primary_energy_value': 'DOUBLE',
    'report_type': 'VARCHAR',
    'uprn_source': 'VARCHAR'
}) s
ANTI JOIN non_domestic_certificates t USING (certificate_number);
